### ISSUE TITLE
Am I suppose to install the original script or just yours separately?

### ISSUE THREAD

**Issue by VHSJayden** [induna-crewneck/argon1-dietpi#1]
Hello. I'm trying to get your script to run but I'm having trouble. Am I suppose to install the original script first or just yours separately?

**Comment by induna-crewneck** [comment]
Hey, no separate scripts. If you download my stuff just overwrite the existing ones. Hope that helps

**Comment by VHSJayden** [comment]
Okay, thanks. So you want me to install your script on top of the original? The only way that I was able to get your script to work was if I installed the original argon one script and then install yours. It seems to work now.

**Comment by induna-crewneck** [comment]
Interesting. Glad you worked it out though
